# Generated by Django 5.0.7 on 2024-07-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseCompassApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aiMessage',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userMessage',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='messages',
            field=models.JSONField(default=list),
        ),
    ]
